language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: oOsTMRFeK9iyK3VYSJd3Lp2it8cr9K0tsn7P7UQKWyh0ctcxezPv37HVNrc/HZC9n7+0dXccu2UG4NbTNf4WLJ4OteHCPD7tSUMGLrwHdnWqiH1euUlGTZhvZm6PVXTvXVYnx5FNVo2jZq0y3Px4V8bZwXt/FjGCn4w713BJ2ZkS1yRXHwbbeZsdSP6NHR3y9BvgUMQqLtMxRoL0JxXzEtbkwkuC9qJYHSlXoXATh99BYPGJwzEn3xTupm5yzduY7PHtAAyBo6Wwd8nf2hAXHDEq1H1h0MiKvGGrH8WsWgM9QsdfZ/A8ds5bKwYweyeTOQpnpZD1IhZShPjbjjyYDsfUBgwBGkFLbhjL0wUGWoaoCFxeQ6sBfSmVCQyjShmHQAF3BFAXYN+H3hjlLomPpXTYPeire1HuEeVIZ7X3wxUHqFlnL2E8FVvdOZcza26W4fliLWNpboVJoFlBZh6r1MOg3LlBhIEyBmwsu8xuwCEWE8t3EKjZk/3YeCayNeh7n+iXWr80MFSPuLEncTK/8v3e2ns9kvpWN2l7msQNhvmZ3HW61nQ9jp7V7OPM4ckKyvyRL9a/y9ytP6Ciz7Jsg+erfcmxmII3zg8ZISW2JALueQxACpo3cE2r7EBurFevOYgQi1QZC/NDYYGOi3wm0q8nfvbZs6ZHlLeWaIZ+7GY=
  app: shopping-list-test
  on:
    repo: rlynn523/mongo-shopping-list
